- name: Ensure required dependencies are installed
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - wget
      - gnupg
    state: present

- name: Add Elastic GPG key
  ansible.builtin.shell: |
    wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | gpg --dearmor -o /usr/share/keyrings/elastic-keyring.gpg
  args:
    creates: /usr/share/keyrings/elastic-keyring.gpg

- name: Add Elastic repository to sources list
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/elastic-8.x.list
    content: |
      deb [signed-by=/usr/share/keyrings/elastic-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main


- name: Install Logstash
  ansible.builtin.apt:
    name: logstash
    state: present
    update_cache: yes

- name: Ensure Logstash is enabled and started
  ansible.builtin.systemd:
    name: logstash
    enabled: true
    state: started