---
- name: Install dependencies for repository installation
  ansible.builtin.apt:
    name: "{{ dependencies }}"
    state: present

- name: Add Elastic GPG key for repository installation
  ansible.builtin.shell: |
    wget -qO - {{ elastic_gpg_url }} | gpg --dearmor -o {{ gpg_keyring_path }}
  args:
    creates: "{{ gpg_keyring_path }}"

- name: Add Elastic repository for Filebeat
  ansible.builtin.copy:
    dest: "{{ elastic_repo_file }}"
    content: "{{ elastic_repo_content }}"

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Install Filebeat from the repository
  ansible.builtin.apt:
    name: "logstash={{ logstash_version }}"
    state: present

- name: Ensure Logstash is enabled and started
  ansible.builtin.systemd:
    name: logstash
    enabled: true
    state: started